/**
 * Copyright (c) 2009 Juwi MacMillan Group GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JavaCC: Do not edit this line. HTMLParserConstants.java */
package de.juwimm.cms.search.res.html;

/**
 * @author <a href="mailto:carsten.schalm@juwimm.com">Carsten Schalm</a>
 * company Juwi|MacMillan Group Gmbh, Walsrode, Germany
 * @version $Id$
 */
public interface HTMLParserConstants {

	int EOF = 0;
	int ScriptStart = 1;
	int TagName = 2;
	int DeclName = 3;
	int Comment1 = 4;
	int Comment2 = 5;
	int Word = 6;
	int LET = 7;
	int NUM = 8;
	int HEX = 9;
	int Entity = 10;
	int Space = 11;
	int SP = 12;
	int Punct = 13;
	int ScriptText = 14;
	int ScriptEnd = 15;
	int ArgName = 16;
	int ArgEquals = 17;
	int TagEnd = 18;
	int ArgValue = 19;
	int ArgQuote1 = 20;
	int ArgQuote2 = 21;
	int Quote1Text = 23;
	int CloseQuote1 = 24;
	int Quote2Text = 25;
	int CloseQuote2 = 26;
	int CommentText1 = 27;
	int CommentEnd1 = 28;
	int CommentText2 = 29;
	int CommentEnd2 = 30;

	int DEFAULT = 0;
	int WithinScript = 1;
	int WithinTag = 2;
	int AfterEquals = 3;
	int WithinQuote1 = 4;
	int WithinQuote2 = 5;
	int WithinComment1 = 6;
	int WithinComment2 = 7;

	String[] tokenImage = {"<EOF>", "\"<script\"", "<TagName>", "<DeclName>", "\"<!--\"", "\"<!\"", "<Word>", "<LET>", "<NUM>", "<HEX>", "<Entity>", "<Space>", "<SP>", "<Punct>", "<ScriptText>", "<ScriptEnd>", "<ArgName>", "\"=\"", "<TagEnd>", "<ArgValue>", "\"\\\'\"", "\"\\\"\"", "<token of kind 22>", "<Quote1Text>", "<CloseQuote1>", "<Quote2Text>", "<CloseQuote2>", "<CommentText1>", "\"-->\"", "<CommentText2>", "\">\"",};

}
