# mysql
CREATE TABLE `XML_SEARCH_DB` (
  `SITE_ID` INTEGER UNSIGNED NOT NULL,
  `VIEW_COMPONENT_ID` INTEGER UNSIGNED NOT NULL,
  `CONTENT` LONGTEXT,
  `UNIT_ID` INTEGER UNSIGNED,
  `INFO_TEXT` VARCHAR(255),
  `TEXT` VARCHAR(255),
  `HASHCODE` VARCHAR(255),
  `CREATED` TIMESTAMP,
  PRIMARY KEY (`SITE_ID`, `VIEW_COMPONENT_ID`)
)
ENGINE = InnoDB
CHARACTER SET utf8 COLLATE utf8_general_ci;

# oracle
CREATE TABLE XML_SEARCH_DB
(
  SITE_ID            NUMBER(10)                 NOT NULL,
  VIEW_COMPONENT_ID  NUMBER(10)                 NOT NULL,
  CONTENT            SYS.XMLTYPE,
  UNIT_ID            NUMBER(10),
  INFO_TEXT          VARCHAR2(255),
  TEXT               VARCHAR2(255),
  HASHCODE           VARCHAR2(255),
  CREATED            TIMESTAMP(3)
);

# mssql 
CREATE TABLE XML_SEARCH_DB
(
  SITE_ID            INTEGER                 NOT NULL,
  VIEW_COMPONENT_ID  INTEGER                 NOT NULL,
  CONTENT            XML,
  UNIT_ID            INTEGER,
  INFO_TEXT          VARCHAR(255),
  TEXT               VARCHAR(255),
  HASHCODE           VARCHAR(255),
  CREATED            DATETIME,
  PRIMARY KEY CLUSTERED(SITE_ID, VIEW_COMPONENT_ID)
);